S2task1 - ugly form and image links working
nickclifford904/chaircollectionapp pull request #4
Opened 2021-03-30 14:04 UTC by nickclifford904

2021-03-30 14:26 UTC, imypullan commented on index.php
> +        Chair name : <input type="text" name="chairname" size="50" placeholder="Enter the name of the chair" /><br>
maybe put these in `div` instead?

2021-03-31 07:56 UTC, ashleycoles requested changes
Just a few minor changes, really nice work!

2021-03-31 07:56 UTC, ashleycoles commented on index.php
> +    </form></div>
Just double check your indenting here, the form should be one level further to show its in the div

2021-03-31 07:56 UTC, ashleycoles commented on index.php
> +echo $result;
Make sure this is happening inside of your <body> tag - all visible content must be contained within the body

2021-03-31 08:07 UTC, merged